# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/strawberry/acy/develop2/metis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/strawberry/acy/develop2/metis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/metis/CMakeFiles /home/strawberry/acy/develop2/metis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/metis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named metis

# Build rule for target.
metis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metis
.PHONY : metis

# fast build rule for target.
metis/fast:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/build
.PHONY : metis/fast

cattr.o: cattr.cpp.o

.PHONY : cattr.o

# target to build an object file
cattr.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/cattr.cpp.o
.PHONY : cattr.cpp.o

cattr.i: cattr.cpp.i

.PHONY : cattr.i

# target to preprocess a source file
cattr.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/cattr.cpp.i
.PHONY : cattr.cpp.i

cattr.s: cattr.cpp.s

.PHONY : cattr.s

# target to generate assembly for a file
cattr.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/cattr.cpp.s
.PHONY : cattr.cpp.s

charref.o: charref.cpp.o

.PHONY : charref.o

# target to build an object file
charref.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/charref.cpp.o
.PHONY : charref.cpp.o

charref.i: charref.cpp.i

.PHONY : charref.i

# target to preprocess a source file
charref.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/charref.cpp.i
.PHONY : charref.cpp.i

charref.s: charref.cpp.s

.PHONY : charref.s

# target to generate assembly for a file
charref.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/charref.cpp.s
.PHONY : charref.cpp.s

ctext.o: ctext.cpp.o

.PHONY : ctext.o

# target to build an object file
ctext.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/ctext.cpp.o
.PHONY : ctext.cpp.o

ctext.i: ctext.cpp.i

.PHONY : ctext.i

# target to preprocess a source file
ctext.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/ctext.cpp.i
.PHONY : ctext.cpp.i

ctext.s: ctext.cpp.s

.PHONY : ctext.s

# target to generate assembly for a file
ctext.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/ctext.cpp.s
.PHONY : ctext.cpp.s

lex.o: lex.cc.o

.PHONY : lex.o

# target to build an object file
lex.cc.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/lex.cc.o
.PHONY : lex.cc.o

lex.i: lex.cc.i

.PHONY : lex.i

# target to preprocess a source file
lex.cc.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/lex.cc.i
.PHONY : lex.cc.i

lex.s: lex.cc.s

.PHONY : lex.s

# target to generate assembly for a file
lex.cc.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/lex.cc.s
.PHONY : lex.cc.s

metis_base.o: metis_base.cpp.o

.PHONY : metis_base.o

# target to build an object file
metis_base.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_base.cpp.o
.PHONY : metis_base.cpp.o

metis_base.i: metis_base.cpp.i

.PHONY : metis_base.i

# target to preprocess a source file
metis_base.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_base.cpp.i
.PHONY : metis_base.cpp.i

metis_base.s: metis_base.cpp.s

.PHONY : metis_base.s

# target to generate assembly for a file
metis_base.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_base.cpp.s
.PHONY : metis_base.cpp.s

metis_celm.o: metis_celm.cpp.o

.PHONY : metis_celm.o

# target to build an object file
metis_celm.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_celm.cpp.o
.PHONY : metis_celm.cpp.o

metis_celm.i: metis_celm.cpp.i

.PHONY : metis_celm.i

# target to preprocess a source file
metis_celm.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_celm.cpp.i
.PHONY : metis_celm.cpp.i

metis_celm.s: metis_celm.cpp.s

.PHONY : metis_celm.s

# target to generate assembly for a file
metis_celm.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/metis_celm.cpp.s
.PHONY : metis_celm.cpp.s

parse.o: parse.cc.o

.PHONY : parse.o

# target to build an object file
parse.cc.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/parse.cc.o
.PHONY : parse.cc.o

parse.i: parse.cc.i

.PHONY : parse.i

# target to preprocess a source file
parse.cc.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/parse.cc.i
.PHONY : parse.cc.i

parse.s: parse.cc.s

.PHONY : parse.s

# target to generate assembly for a file
parse.cc.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/parse.cc.s
.PHONY : parse.cc.s

sd-utf8code.o: sd-utf8code.cpp.o

.PHONY : sd-utf8code.o

# target to build an object file
sd-utf8code.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/sd-utf8code.cpp.o
.PHONY : sd-utf8code.cpp.o

sd-utf8code.i: sd-utf8code.cpp.i

.PHONY : sd-utf8code.i

# target to preprocess a source file
sd-utf8code.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/sd-utf8code.cpp.i
.PHONY : sd-utf8code.cpp.i

sd-utf8code.s: sd-utf8code.cpp.s

.PHONY : sd-utf8code.s

# target to generate assembly for a file
sd-utf8code.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/sd-utf8code.cpp.s
.PHONY : sd-utf8code.cpp.s

strescape.o: strescape.cpp.o

.PHONY : strescape.o

# target to build an object file
strescape.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strescape.cpp.o
.PHONY : strescape.cpp.o

strescape.i: strescape.cpp.i

.PHONY : strescape.i

# target to preprocess a source file
strescape.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strescape.cpp.i
.PHONY : strescape.cpp.i

strescape.s: strescape.cpp.s

.PHONY : strescape.s

# target to generate assembly for a file
strescape.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strescape.cpp.s
.PHONY : strescape.cpp.s

stringdata.o: stringdata.cpp.o

.PHONY : stringdata.o

# target to build an object file
stringdata.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/stringdata.cpp.o
.PHONY : stringdata.cpp.o

stringdata.i: stringdata.cpp.i

.PHONY : stringdata.i

# target to preprocess a source file
stringdata.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/stringdata.cpp.i
.PHONY : stringdata.cpp.i

stringdata.s: stringdata.cpp.s

.PHONY : stringdata.s

# target to generate assembly for a file
stringdata.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/stringdata.cpp.s
.PHONY : stringdata.cpp.s

strvisitor.o: strvisitor.cpp.o

.PHONY : strvisitor.o

# target to build an object file
strvisitor.cpp.o:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strvisitor.cpp.o
.PHONY : strvisitor.cpp.o

strvisitor.i: strvisitor.cpp.i

.PHONY : strvisitor.i

# target to preprocess a source file
strvisitor.cpp.i:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strvisitor.cpp.i
.PHONY : strvisitor.cpp.i

strvisitor.s: strvisitor.cpp.s

.PHONY : strvisitor.s

# target to generate assembly for a file
strvisitor.cpp.s:
	$(MAKE) -f CMakeFiles/metis.dir/build.make CMakeFiles/metis.dir/strvisitor.cpp.s
.PHONY : strvisitor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... metis"
	@echo "... cattr.o"
	@echo "... cattr.i"
	@echo "... cattr.s"
	@echo "... charref.o"
	@echo "... charref.i"
	@echo "... charref.s"
	@echo "... ctext.o"
	@echo "... ctext.i"
	@echo "... ctext.s"
	@echo "... lex.o"
	@echo "... lex.i"
	@echo "... lex.s"
	@echo "... metis_base.o"
	@echo "... metis_base.i"
	@echo "... metis_base.s"
	@echo "... metis_celm.o"
	@echo "... metis_celm.i"
	@echo "... metis_celm.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... sd-utf8code.o"
	@echo "... sd-utf8code.i"
	@echo "... sd-utf8code.s"
	@echo "... strescape.o"
	@echo "... strescape.i"
	@echo "... strescape.s"
	@echo "... stringdata.o"
	@echo "... stringdata.i"
	@echo "... stringdata.s"
	@echo "... strvisitor.o"
	@echo "... strvisitor.i"
	@echo "... strvisitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

